### PR TITLE
Jw iconbug

### LINKED ISSUE #3: BUG: Inaccurate Icon
### Have you updated the title?

- [X] I have updated the issue's title.

### Summary

Currently, the icon for project organic is a cow (a happy one at that). This is not accurate and does not properly represent the web application.  (5)

### Expected Behavior

The icon of the app should adequately and properly represent what the app does and what it represents.

### Current / Observed Behavior

The current icon is a cow. However the codename of the application isn't anything related to cows.

### Steps to Reproduce

1. Look at your tab at the top of the screen next to "Organic"
2.
3.
4.

### Browser / Platform Info

_No response_

### PR DESCRIPTION
**Pull request by Jenniebn**
In this PR, I fixed the icon bug.

Closes #3 
Screenshot 2024-02-27 at 18 19 19

Link to content license: https://pixabay.com/service/license-summary/
Link to the picture: https://pixabay.com/illustrations/avocado-fruit-cartoon-artistic-8186060/

### CODE REVIEW

**Review by jenniferlopez17 — DISMISSED** [review]
LGTM!

**Review by whuang602 — CHANGES_REQUESTED** [review]
The image displayed in the PR and the changed images do not seem to match. Also please make sure the image you end up using is copyright free.

**Comment by Jenniebn** [comment]
I fixed the problem with copyright free picture.
Screenshot 2024-02-28 at 18 57 08
deployed: http://organic-jenniebn-dev.dokku-11.cs.ucsb.edu

**Review by kenisha-v — APPROVED** [review]
LGTM!

**Review by welaalice — APPROVED** [review]
LGTM!

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
