### PR TITLE
Jw feature course

### PR DESCRIPTION
**Pull request by Jenniebn**
In this PR, I created the feature to allow regular users to access course page but they cannot see edit/ delete/ create buttons. For admin users, they can still see edit/ delete/ create buttons

Screenshot 2024-03-01 at 14 22 10
Screenshot 2024-03-01 at 14 23 21

deployment: https://organic-jenniebn-dev.dokku-11.cs.ucsb.edu/

### CODE REVIEW

**Review by whuang602 — CHANGES_REQUESTED** [review]
The Deployment is broken when I try to access it, it currently leads me to a 404 page when I try to login

**Comment by Jenniebn** [comment]
The deployment should work now

**Review by welaalice — APPROVED** [review]
LGTM!

**Review by whuang602 — APPROVED** [review]
Toggle is slightly inconsistent, if you can figure out and fix this problem, we can award more points. Otherwise it's good

**Review by andyjin1 — APPROVED** [review]
LGTM

**Review by kenisha-v — APPROVED** [review]
lgtm!

**Pull request merged**
