### PR TITLE
JL - Bug Admin can Toggle Their Admin Rights Of

### LINKED ISSUE #2: BUG: Admin can Toggle Their Admin Rights Off
### Have you updated the title?

- [X] I have updated the issue's title.

### Summary

Currently, as an admin you can turn off your own admin rights. Theoretically you can make this be worth more points if you implement a more sophisticated system, e.g. allow the admin to toggle themselves but warn them and ask them if they are sure first. (5 or 10)

### Expected Behavior

If you were an admin, you shouldn't be able to turn off your own admin privileges.

### Current / Observed Behavior

If an admin toggles off their privileges, they are instantly locked out of the app and cannot perform any further actions.

### Steps to Reproduce

1. Under the admin page and within the users page
2. Toggle Admin off for yourself (make sure there's someone who can retoggle it for you)
3. 
4.

### Browser / Platform Info

_No response_

### PR DESCRIPTION
**Pull request by jenniferlopez17**
In this pr, I added a popup which asks the admin if they want to toggle their rights off before completing the request.

Deployed at:
http://organic-jenniferlopez17-dev.dokku-11.cs.ucsb.edu
Screenshot 2024-02-28 at 12 17 32 AM

Closes #2

### CODE REVIEW

**Review by Jenniebn — APPROVED** [review]
LGTM

**Review by welaalice — DISMISSED** [review]
LGTM!

**Review by whuang602 — COMMENTED** [review]
would love to see a dokku link so I can test it.

**Comment by jenniferlopez17** [comment]
Here is my dokku deployment link:
http://organic-jenniferlopez17-dev.dokku-11.cs.ucsb.edu

**Review by welaalice — APPROVED** [review]
The pop up works!

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
