### PR TITLE
TP - School Entity and Repository

### LINKED ISSUE #45: entity and repository class for schools table

### PR DESCRIPTION
**Pull request by welaalice**
In this PR, I created the school entity and repository for the school table. [Backend]

Closes #45

### CODE REVIEW

**Review by Jenniebn — APPROVED** [review]
LGTM!

**Review by jenniferlopez17 — APPROVED** [review]
LGTM!

**Review by kenisha-v — APPROVED** [review]
LGTM!

**Review by andyjin1 — APPROVED** [review]
LGTM

**Review by whuang602 — APPROVED** [review]
Looks good, but must wait until a previous PR is fixed, approved, merged.

**Pull request merged**
