### PR TITLE
JL -  FEATURE Popups for Admin Toggles

### LINKED ISSUE #5: FEATURE: Pop-ups for Admin Toggles
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

admin

### I can...

receive a pop-up when I try to toggle roles

### So that...

I can accurately decide whether I want to alter roles

### Discussion

Currently, admins can modify other users' roles with one click. This can be detrimental if it wasn't done intentionally, this can also potentially result in problems for other admins. A pop-up or confirmation request would be a great change that ensures security and user safety. (10)

### Acceptance Criteria

- [x] When an admin clicks on "toggle-admin" they get a pop up that asks them if they are sure they want to toggle admin role
- [x] When an admin clicks on "toggle-instructor" they get a pop up that asks them if they are sure they want to toggle instructor role

### Implementation Todos

Frontend:
- [x] Add a confirmation popup before the toggle backend is triggered (feel free to look up how to do this)

Testing:
- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by jenniferlopez17**
In this pr, I added popups for when an admin attempts to toggle admin or instructor roles.
Deployed at: http://organic-jenniferlopez17-dev.dokku-11.cs.ucsb.edu

Closes #5 
Screenshot 2024-02-29 at 11 25 44 PM
Screenshot 2024-02-29 at 11 25 58 PM

### CODE REVIEW

**Review by welaalice — APPROVED** [review]
LGTM!

**Review by Jenniebn — APPROVED** [review]
I cannot access the dokku deployment probably bc my github id is wrong on your environment config, but based on the screen shots they look good to me!

**Comment by jenniferlopez17** [comment]
> I cannot access the dokku deployment probably bc my github id is wrong on your environment config, but based on the screen shots they look good to me!

I reset the admin usernames just in case your username was case sensitive!

**Review by whuang602 — CHANGES_REQUESTED** [review]
Currently, regardless of whether you are revoking or granting admin rights, the pop up asks if you want to "revoke" admin rights

**Comment by jenniferlopez17** [comment]
> Currently, regardless of whether you are revoking or granting admin rights, the pop up asks if you want to "revoke" admin rights

I made changes for that!

**Review by welaalice — APPROVED** [review]
The pop up message is general now, LGTM!
image

**Review by whuang602 — CHANGES_REQUESTED** [review]
If you can fix the merge request, then I will be able to approve of the PR

**Comment by jenniferlopez17** [comment]
> If you can fix the merge request, then I will be able to approve of the PR

I fixed the merge conflicts!

**Review by whuang602 — APPROVED** [review]
LGTM

**Review by welaalice — APPROVED** [review]
LGTM

**Pull request merged**
