### PR TITLE
TP - instructors create course

### LINKED ISSUE #9: FEATURE: Instructors can create courses
# Dependencies

This issue cannot be started until after there has been enough progress on the Epic for creating the Instructor role so that ROLE_INSTRUCTOR exists in the database.

# User Story

* As an instructor
* I can create a new course
* So that I don't have to rely on admins to create courses

### Discussion

This issue cannot be started until after there has been enough progress on the Epic for creating the Instructor role so that ROLE_INSTRUCTOR exists in the database.

Currently, only Admins can create courses.

In this issue, we'll modify that so that Instructors can also create courses.

Once an instructor creates a course, they will be automatically a staff member for that course so that will be the way in which we determine whether or not they have permissions to do course management features.  So only the creation of the course is affected.

For now, we'll assume that only admins can delete a course.

### Acceptance Criteria

- [x] Anyone with ROLE_ADMIN or ROLE_INSTRUCTOR can create a course.
- [x] The frontend access to creating a course only shows up for users with  ROLE_ADMIN or ROLE_INSTRUCTOR

### PR DESCRIPTION
**Pull request by welaalice**
In this PR, instructors can create courses now. The feature concerning the frontend access to creating a course only shows up for users with ROLE_ADMIN or ROLE_INSTRUCTOR has been completed by Jennie through #41 

Admin off, Instructor on:
image

Can Create Course:
image
image

Closes #9 
Deployed at: https://organic-welaalice.dokku-11.cs.ucsb.edu

### CODE REVIEW

**Review by kenisha-v — APPROVED** [review]
LGTM!

**Review by jenniferlopez17 — APPROVED** [review]
I can successfully add a course LGTM!

**Review by whuang602 — CHANGES_REQUESTED** [review]
On the deployment, if I was to make myself an instructor and remove admin privileges. I do see the Create Course button but I am not able to create the course after filling out all inputs.

**Review by Jenniebn — APPROVED** [review]
Deployment link worked! LGTM

**Review by kenisha-v — APPROVED** [review]
LGTM!

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
