### PR TITLE
KV - Staff Table components and Fixtures

### LINKED ISSUE #28: There is a table component to list staff members, and fixures that match the `GET /api/course/staff/all?courseId=123` endpoint

### PR DESCRIPTION
**Pull request by kenisha-v**
In this PR, I created table component and fixures for the Staff Table.

storybook link: https://ucsb-cs156-w24.github.io/proj-organic-w24-6pm-3/prs/44/storybook/?path=/story/components-staff-stafftable--three-items-ordinary-user

Screenshot 2024-03-05 at 5 20 01 PM

Closes #28

### CODE REVIEW

**Review by welaalice — DISMISSED** [review]
LGTM!

**Review by jenniferlopez17 — DISMISSED** [review]
LGTM!

**Review by andyjin1 — DISMISSED** [review]
LGTM!

**Review by whuang602 — CHANGES_REQUESTED** [review]
Please just delete commented out code. Commented out code indicates you aren't confident about the change. This can delete to build up of old code and comments and bog down future development. If it's going to be deleted eventually, why not delete it now?

**Review by whuang602 — APPROVED** [review]
LGTM

**Review by Jenniebn — APPROVED** [review]
LGTM

**Review by andyjin1 — APPROVED** [review]
LGTM

**Review by jenniferlopez17 — APPROVED** [review]
LGTM!

**Review by welaalice — APPROVED** [review]
LGTM!

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
